{
  parserClass="cadence.language.CadenceParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Cadence"
  psiImplClassSuffix="Impl"
  psiPackage="cadence.language.psi"
  psiImplPackage="cadence.language.impl"

  elementTypeHolderClass="cadence.language.psi.CadenceTypes"
  elementTypeClass="cadence.language.psi.CadenceElementType"
  tokenTypeClass="cadence.language.psi.CadenceTokenType"
}

cadenceFile ::= item_*

private item_ ::= (KEYWORD|separator|comment|value|identifier|TYPE)

value ::= (NUMERIC_VALUE|STRING_VALUE|STRING_ESCAPE_SEQUENCE)
comment ::= (SIMPLE_COMMENT|DOCUMENTATION_COMMENT)
identifier ::= (DEFINITION|FUNCTION_NAME|FUNCTION_PARAMETER)
separator ::= (OPERATOR)
